apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: allow-log-access
  namespace: log-test-0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-application-logs-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: testuser-0
